### ISSUE TITLE
Overflow of navigation bar

### ISSUE THREAD

**Issue by ghost** [marcantondahmen/automad-baker#2]
Hello, it's me again ;)

The navbar in the header overflows on mobile devices, instead of getting hidden. I don't think that's the desired behaviour.

This also moves the hamburger menu out of view, so you are entirely unable to navigate.

**Comment by marcantondahmen** [comment]
Hi there, I will take a look at it asap!

**Comment by marcantondahmen** [comment]
Finally fixed in the latest version ...
🙂
