### ISSUE TITLE
Issues with the Baker theme v0.1.5

### ISSUE THREAD

**Issue by 72frank** [marcantondahmen/automad-baker#3]
Hi Marc,
I think the new sections are awsome and while I very much like the new full window display of images in a gallery block I also found these possible 'bugs':

_Baker theme v0.1.5 in combination with Automad v1.6.12_
1. The main content of blog pages is not displayed centered anymore, but drawn to the left hand side and also stretched over the screen.
2. Image caching does not seem to work correctly meaning that images in a gallery block are shown with full path links (i.e. with the trailing order prefix) and original file name instead of the cached path and name.

_Baker theme v0.1.5 in combination with Automad v1.7.2_
1. The filter checkbox on blog pages is not shown aligned with the title and text paragraph anymore but off to the left instead.
2. Image caching does not seem to work correctly meaning that images in a gallery block are shown with full path links (i.e. with the trailing order prefix) and original file name instead of the cached path file name.

I also tested the above with a clean install; all on MacBook with MAMP 5.7 and:
_Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.4.2 mod_ssl/2.2.34 OpenSSL/1.0.2o DAV/2 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.24.0
PHP: 7.4.2 / apache2handler_

I intend to be contributing towards a more stable version and hope that it's not just some isolated issue on my local installation!

Best regards,
Frank

**Comment by marcantondahmen** [comment]
Hi there,  

thanks for reporting this. Unfortunately version 0.1.5 is only supposed to work with the latest Automad version. However, you are right about the filter button position. I have fixed it already.    

Regarding the image caching i'm not able to reproduce that issue. But in case you actually mean the **pagelist** block instead, it is the intended behavior. As long as you don't define explicitly a teaser image for a page, the first image URL found in a page will be used as the image URL for the preview and therefore caching will be skipped. In pagelist blocks, only defined teaser images are resized and cached.

**Comment by 72frank** [comment]
Hi Marc,
many thanks for fixing the filter button position and explaining the compatibility (which I understand).
Best regards,
Frank

**Comment by 72frank** [comment]
Regarding

> Image caching does not seem to work correctly meaning that images in a gallery block are shown with full path links (i.e. with the trailing order prefix) and original file name instead of the cached path file name.

let me explain some more:

In Automad v1.7.2 with Baker theme v0.1.5 I created the folder structure as _Home >01.Photography  >02.Flowers_ where I saved 8 JPEG files.
The Post page _02.Flowers_ contains a gallery block with filter *.jpg and the Cache is enabled.

a) On the Blog page _01.Photography_ the (cached) image in the pagelist is shown correctly with `href=` /**photography/flowers** and `img src=` **/cache/images/cached_ef53.....0bff.jpg**

b) On the Post page _02.Flowers_ the images are shown with `href=`  **/01.photography/02.flowers/img-02xx.jpg** where I would have expected _**/photography/flowers/img-02xx.jpg**_ instead.

However I just found out that the `img src` c**orrectly points to the cached objects for the gallery images**, which means that it is **NOT an issue with the cache** but most probably _with my understanding of Automad..._

I might have missed something in your documentation and obviously was under a wrong impression as how links to images are handled. So I will have to emphasize a bit more on page/folder names as well as image file naming (for I thought it to be much easier to just save a bunch of jpeg files in a folder and be done with it).

In any case thanks for your great work!
Best regards,
Frank
